

Courses={
"CSE":{
    "CSE 5000":[ "Introduction to Formal Languages and Automata Theory", "Formal language theory", "Finite state machines", "Regular grammars", "Context-free grammars", "Context-sensitive grammars", "Push-down automata", "Turing machine", "Closure properties"],
    "CSE 5010":[ "Introduction to Theory of Computation", "Turing machines", "Models of computation", "Recursive functions", "Churchs thesis", "Undecidable problems", "Complexity classes (P", "NP", "CO-NP", "PSPACE)"],
    "CSE 5100":[ "Advanced Computer Architecture", "High performance computer architectures", "Pipeline", "Vector processors", "Array processors", "Multiprocessor computer designs", "Data flow", "Systolic machines", "Interconnection networks", "Parallel graph algorithms"],
    "CSE 5120":[ "Introduction to Artificial Intelligence", "Foundations of artificial intelligence", "Current techniques", "Problems", "Limitations", "Future prospects of machine intelligence"],
    "CSE 5140":[ "Computational Intelligence", "Neural networks", "Fuzzy logic", "Evolutionary computation", "Soft-computing", "Optimization", "Pattern recognition", "Deep learning", "Decision making", "Prediction"],
    "CSE 5150":[ "Automated Reasoning", "Logical deduction algorithms", "Propositional calculus", "Predicate calculus", "Completeness and incompleteness theorems", "Automation of theorem proving techniques"],
    "CSE 5160":[ "Machine Learning", "Reinforced learning", "Supervised learning", "SVMs", "Data clustering", "Multi-agent systems", "Computer vision", "Knowledge discovery", "Big data"],
    "CSE 5200":[ "Advanced Computer Graphics", "Shading models", "Parametric curves", "Parametric surfaces", "Hidden surface removal", "Anti-aliasing"],
    "CSE 5208":[ "Introduction to Computer Engineering Design", "Engineering design principles", "Requirements analysis", "System specifications", "Project management", "Human-computer interface", "Engineering ethics", "Technical writing"],
    "CSE 5210":[ "Digital System Design", "FPGA", "Control and datapath", "Architecture and synthesis", "I/O peripherals"],
    "CSE 5250":[ "Parallel Algorithms and Programming", "Algorithm design", "Analysis", "Programming of high-performance computers", "Control-parallel", "Data-parallel approaches", "Parallel programming languages"],
    "CSE 5300":[ "Data Communications", "Analog and digital communications", "Signal modulation", "Digitization", "Synchronization", "Channel coding", "Communication protocols", "Base-band signal transmission"],
    "CSE 5350":[ "Numerical Computation", "Scientific computing", "Approximations", "Zero findings", "Least squares", "Eigenvalue problems", "Numerical differentiation", "Numerical integration", "Data fitting", "Interpolation", "Optimizations", "Nonlinear equations"],
    "CSE 5408":[ "Sustainable Engineering Design", "System architectural design", "Concurrent hardware and software design", "System integration", "Testing", "Validation", "Maintainability", "Sustainability", "Safety", "Fault tolerance", "Project documentation"],
    "CSE 5410":[ "Robotics and Control", "Forward kinematics", "Reverse kinematics", "PID control", "Robotic construction", "Robotic programming"],
    "CSE 5500":[ "Advanced Bioinformatics I: Sequence Analysis", "Computational techniques", "Genomics", "Bioinformatics tools", "DNA analysis", "RNA analysis", "Protein sequence analysis"],
    "CSE 5510":[ "Advanced Bioinformatics II: Numerical Modeling", "Numerical techniques", "Modeling", "Simulation", "Biological systems", "Chemical systems", "Differential equations", "Stochastic variables"],
    "CSE 5700":[ "Compilers", "Interpreter structures", "Compiler structures", "Symbol tables", "Lexical analyzers", "Syntactic analyzers", "Object code generation"],
    "CSE 5720":[ "Database Systems", "Database design", "Storage structures", "Database models (relational", "object-relational", "network", "hierarchical)", "Database management systems"],
    "CSE 5750":[ "Internship in Computer Science and Engineering", "Supervised work", "Study in private or public organizations", "Project proposal", "Graded credit/no credit"],
    "CSE 5800":[ "Advanced Database Systems", "Database components", "Implementation methods", "Query language design", "Reliability", "Integrity", "Performance measures", "Distributed database systems", "Database machines"],
    "CSE 5940":[ "Topics in Computer Science and Engineering", "In-depth consideration", "Selected areas of computer science and engineering", "Credit may be repeated for different topics"],
    "CSE 5951":[ "Independent Study (1 unit)", "Laboratory research", "Library research", "Faculty-directed research", "Project proposal"],
    "CSE 5952":[ "Independent Study (2 units)", "Laboratory research", "Library research", "Faculty-directed research", "Project proposal"],
    "CSE 5953":[ "Independent Study (3 units)", "Laboratory research", "Library research", "Faculty-directed research", "Project proposal"],

    "CSE 6020":[ 'Computation', 'Complexity Theory', 'Turing machines', 'Models of computation', 'Recursive functions', 'Undecidable problems', 'Complexity classes (P', 'NP', 'CO-NP', 'PSPACE)']
    ,"CSE 6030":[ 'Advanced Computation', 'Complexity Theory', 'Churchs thesis', 'Time complexity', 'Space complexity', 'Randomized computation', 'Interactive proofs', 'Circuit computational model', 'Circuit complexity', 'Cryptography', 'Quantum complexity']
    ,"CSE 6100":[ 'Modern Computer Architecture', 'Parallel systems', 'Vector processors', 'Network scheduling', 'Pipelining', 'Array processors', 'Systolic arrays']
    ,"CSE 6110":[ 'VLSI Circuit Design', 'Very Large Scale Integrated (VLSI) circuits', 'Semiconductor devices', 'Design rules', 'Circuit layouts', 'Computer-aided design tools']
    ,"CSE 6200":[ 'Programming Languages Theory', 'User interfaces', 'Parallelism', 'Distributed processing', 'Functional programming languages', 'Object-oriented programming languages']
    ,"CSE 6210":[ 'Contemporary Computer Graphics', '3-D modeling', 'Ray tracing', 'Object representation', 'Visualization', 'Animation techniques']
    ,"CSE 6240":[ 'Distributed Computer Systems', 'Message passing', 'Shared data', 'Distributed control', 'Operating systems', 'Synchronization', 'Deadlock']
    ,"CSE 6250":[ 'Multiprocessor and Parallel Processing', 'Multiprocessors', 'Interconnection network', 'Parallel programming languages', 'Scheduling', 'Problem decomposition', 'Communication']
    ,"CSE 6300":[ 'Theory of Algorithms and Their Analysis', 'Algorithmic techniques', 'Time complexity', 'Space complexity', 'Graph algorithms', 'Randomized algorithms', 'Parallel algorithms']
    ,"CSE 6310":[ 'Advanced Data Communications', 'High bandwidth networks', 'Traffic control', 'Congestion control', 'Routing theory', 'Quality of service', 'Internet protocol suite']
    ,"CSE 6340":[ 'Neural Networks', 'Perceptrons', 'Recurrent networks', 'Self-organizing maps', 'Multi-layer networks', 'Deep learning']
    ,"CSE 6350":[ 'Numerical Algorithms and Simulation', 'Scientific computing', 'Systems of linear equations', 'Linear least squares', 'Simulation', 'Sparse matrices']
    ,"CSE 6400":[ 'Artificial Intelligence', 'Knowledge representations', 'Heuristics', 'Problem-solving', 'Adaptive systems', 'Natural language understanding', 'Machine learning', 'Robotics systems']
    ,"CSE 6550":[ 'Software Engineering Concepts', 'Software requirements', 'Software systems design', 'Verification', 'Validation', 'Software maintenance', 'Rapid prototyping']
    ,"CSE 6560":[ 'Formal Methods', 'Models and Languages', 'Logic', 'Mathematics', 'Formal modeling languages', 'Model checking']
    ,"CSE 6600":[ 'Operating Systems Concepts and Theory', 'Operating system concepts', 'Scheduling practices', 'Multiprocessing', 'Distributed file systems', 'Peripheral access scheduling']
    ,"CSE 6700":[ 'Compiler Design Theory', 'Lexical analyzers', 'Parsers', 'Code optimization']
    ,"CSE 6710":[ 'Advanced Compilers', 'Intermediate code generation', 'Optimization', 'Object code generation', 'Compiler co-design']
    ,"CSE 6800":[ 'Distributed Database Management Systems', 'Data distribution', 'Remote database access', 'Concurrency management', 'SQL', 'Cooperative processing', 'Intelligent databases']
    ,"CSE 6890":[ 'Graduate Seminar', 'Current research areas', 'Review topics', 'Computer Science program']
    ,"CSE 6940":[ 'Graduate Research Methods in Computer Science', 'Research methods', 'Literature review', 'Directed individual study']
    ,"CSE 6950":[ 'Graduate Independent Study', 'Independent research', 'Written proposal', 'Department approval']
    ,"CSE 6962":[ 'Masters Project', 'Independent project', 'Major advisor guidance']
    ,"CSE 6964":[ 'Masters Project', 'Independent project', 'Major advisor guidance']
    ,"CSE 6972":[ 'Thesis', 'Independent research', 'Major advisor guidance']
    ,"CSE 6973":[ 'Thesis', 'Independent research', 'Major advisor guidance']
    ,"CSE 6974":[ 'Thesis', 'Independent research', 'Major advisor guidance']
    ,"CSE 6976":[ 'Thesis', 'Independent research', 'Major advisor guidance']
    ,"CSE 6980":[ 'Comprehensive Examination', 'Formal language', 'Automata theory', 'Computer architecture', 'Algorithms', 'Software engineering', 'Operating systems']
    ,"CSE 6990":[ 'Continuous Enrollment for Graduate Candidacy Standing', 'Independent study', 'Graduate candidacy requirements']
    ,"CSE 6991":[ 'Continuous Enrollment for Graduate Candidacy Standing', 'Independent study', 'Graduate candidacy requirements']
    ,"CSE 6992":[ 'Continuous Enrollment for Graduate Candidacy Standing', 'Independent study', 'Graduate candidacy requirements']
    ,"CSE 6993":[ 'Continuous Enrollment for Graduate Candidacy Standing', 'Independent study', 'Graduate candidacy requirements']
    ,"CSE 6994":[ 'Continuous Enrollment for Graduate Candidacy Standing', 'Independent study', 'Graduate candidacy requirements']
    ,"CSE 6995":[ 'Continuous Enrollment for Graduate Candidacy Standing', 'Independent study', 'Graduate candidacy requirements']
    ,"CSE 6996":[ 'Continuous Enrollment for Graduate Candidacy Standing', 'Independent study', 'Graduate candidacy"requirements']},

"IST" : {
    "IST 5050": ["Advanced Enterprise Resource Planning", "ERP", "cross-functional business processes", "integration points", "database configuration"],
    "IST 5150": ["Project Management", "project management theory", "project constraints", "project life cycle", "risk analysis", "resource allocation"],
    "IST 5250": ["Incident Handling and Cyber Investigation", "digital evidence", "forensics", "cyber crimes", "best practices"],
    "IST 5753": ["Apprenticeship", "supervised work", "department of labor", "work and study"],
    "IST 5755": ["Internship", "supervised work", "private organizations", "public organizations"],
    "IST 5915": ["Seminar in Information Systems and Technology", "intensive study", "information systems", "technology"],
    "IST 5930": ["Seminar in Information Systems and Technology", "intensive study", "information systems", "technology"],
    "IST 5951": ["Independent Study", "library research", "field research", "written project/proposal"],
    "IST 5952": ["Independent Study", "library research", "field research", "written project/proposal"],
    "IST 5953": ["Independent Study", "library research", "field research", "written project/proposal"],
    "IST 5955": ["Independent Study", "library research", "field research", "written project/proposal"],

    "IST 6030": ["Foundations of Business Systems", "business systems", "hardware components", "information systems maintenance", "programming techniques"],
    "IST 6090": ["Information Systems and Technology Management", "IT impact", "business models", "information management planning", "cyber security"],
    "IST 6110": ["Foundations of Analytics and Big Data", "business analytics", "data-driven decision making", "statistical concepts", "data visualization"],
    "IST 6115": ["Fundamentals of Cyber Security", "computer security", "access control", "security management", "Internet security"],
    "IST 6117": ["Network Security 1", "network protocols", "network attacks", "network security"],
    "IST 6125": ["Law and Policy", "legal rights", "liabilities", "computer security", "privacy issues"],
    "IST 6215": ["Network Security 2", "network security protocols", "cryptography", "network forensics", "network attacks"],
    "IST 6232": ["Risk Assessment & Management", "risk management frameworks", "contingency planning", "security policy formulation"],
    "IST 6235": ["Cyber Analytics and Visualization", "data analytics", "threat visualization", "malware detection", "data visualization tools"],
    "IST 6385": ["Capstone", "integrative project", "prior courses", "final project"],
    "IST 6395": ["Contemporary Issues and Practices in Cybersecurity 1", "current issues", "cybersecurity practices"],
    "IST 6397": ["Contemporary Issues and Practices in Cybersecurity 2", "current issues", "cybersecurity practices"],
    "IST 6415": ["Information Resources and Project Management", "project management", "project scheduling", "risk assessment"],
    "IST 6450": ["Systems Analysis, Design and Implementation", "systems analysis", "software project", "system prototype"],
    "IST 6470": ["Database Management and Policies", "database design", "database management systems", "data administration"],
    "IST 6480": ["Information Networking Systems and Security", "information networks", "systems architecture", "security management"],
    "IST 6620": ["Business Analytics and Decision Making", "data analytics", "statistical methods", "data visualization"],
    "IST 6670": ["Data Warehousing and Business Intelligence", "data warehouse", "business intelligence", "OLAP"],
    "IST 6680": ["Business Applications Using Web Technologies", "web based business applications", "internet communications", "web security"],
    "IST 6700": ["Cybersecurity Policy and Risk Management", "information security", "risk management", "incident handling"],
    "IST 6720": ["Cyber Defense and Vulnerability Analysis", "information assurance", "security practices", "security scenarios"],
    "IST 6730": ["Cybersecurity Theory and Practice", "cybersecurity tools", "threat mitigation", "confidentiality"],
    "IST 6755": ["Internship", "supervised work", "private organizations", "public organizations"],
    "IST 6780": ["Risk Management", "business risk", "risk identification", "risk analysis"],
    "IST 6800": ["Advanced E-commerce Technologies", "e-commerce technologies", "web site design", "mobile commerce"],
    "IST 6890": ["Enterprise Architecture Planning, Strategy, Security and Policy", "enterprise architecture planning", "security policy", "real organizations"],
    "IST 6960": ["MSCA/MSIST Culminating Project", "comprehensive project", "mastery of subject matter"],
    "IST 6980": ["MSIST Portfolio", "portfolio submission", "reflective essay"],
    "IST 6990": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "IST 6991": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "IST 6992": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "IST 6993": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "IST 6994": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "IST 6995": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "IST 6996": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"]},


"SCM": {
    "SCM 5050": ["Advanced Enterprise Resource Planning", "ERP", "cross-functional business processes", "integration points", "databases", "ERP system"],
    "SCM 5150": ["Project Management", "project management theory", "project management constraints", "time", "cost", "performance", "project life cycle", "sequencing", "budgeting", "project evaluation", "project feasibility", "risk analysis", "resource allocation", "project management tools"],
    "SCM 5250": ["Quality Management", "quality assurance programs", "statistical quality control", "quality design", "measurement", "management of quality", "reliability", "total quality management", "management of six sigma quality", "inspection"],
    "SCM 5753": ["Apprenticeship", "supervised work", "study", "private", "public organizations", "department of labor registered apprenticeship"],
    "SCM 5755": ["Internship", "supervised work", "study", "private", "public organizations"],
    "SCM 5915": ["Seminar in Supply Chain Management", "intensive study", "phase of supply chain management"],
    "SCM 5930": ["Seminar in Supply Chain Management", "intensive study", "phase of supply chain management"],
    "SCM 5951": ["Independent Study", "special topics", "library research", "field research"],
    "SCM 5952": ["Independent Study", "special topics", "library research", "field research"],
    "SCM 5953": ["Independent Study", "special topics", "library research", "field research"],
    "SCM 5955": ["Independent Study", "special topics", "library research", "field research"],
    "SCM 6070": ["Managing the Supply Chain", "analytical techniques", "logistics", "supply chain management", "decision models", "planning", "control", "forecasting", "scheduling", "analysis"],
    "SCM 6110": ["Global Supply Chain Management and Logistics", "global supply chain management", "operations management strategy", "competitive performance"],
    "SCM 6200": ["Integrated Logistics Management", "integrated logistics", "supply chain strategy", "strategic procurement", "material management", "purchasing", "supply management", "logistics information systems", "demand management", "inventory management", "packaging", "material handling systems", "transportation modes", "forward logistics", "reverse logistics"],
    "SCM 6300": ["Warehouse and Distribution Management", "order fulfillment management", "distribution", "omnichannel network design", "warehouse design", "materials handling", "freight transportation", "warehouse cost management", "warehouse management systems"],
    "SCM 6400": ["Supply Chain Security and Blockchain", "supply chain security", "blockchain technology", "supply chain visibility", "transparency", "secure end-to-end supply chain infrastructure", "blockchain-enabled smart contracts", "ISO 28000", "NIST-Cyber Supply Chain Risk Management", "C-TPAT Supply Chain Risk Management System"],
    "SCM 6600": ["Transportation and Supply Chain Management", "managing transportation", "logistics", "pipeline of goods", "channels of distribution"],
    "SCM 6620": ["Business Analytics and Decision Making", "data analytics", "deterministic decision-making", "decision making under uncertainty", "optimization decision analysis tools", "statistical methods", "relational databases", "SQL", "text processing", "sentiment analysis", "data visualization", "Business Intelligence Tools"],
    "SCM 6755": ["Internship", "supervised work", "study", "private", "public organizations"],
    "SCM 6910": ["Culminating Experience Project", "logistics", "e-commerce project", "critical", "independent thinking", "mastery"],
    "SCM 6990": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "SCM 6991": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "SCM 6992": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "SCM 6993": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "SCM 6994": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "SCM 6995": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"],
    "SCM 6996": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree requirements"]
},


"ACCT": {
    "ACCT 5200": ["Forensic Accounting I", "overview", "Forensic Accounting knowledge", "skills", "responsibilities", "ethical", "legal environment", "Fraud", "Bankruptcy", "Digital Forensics", "Family Law", "Economic Damages", "Business Valuations"],
    "ACCT 5360": ["Corporate and Partnership Taxation", "basic concepts", "basic tax forms", "federal income taxation", "corporations", "partnerships", "tax research"],
    "ACCT 5390": ["Advanced Accounting", "accounting", "reporting", "mergers and acquisitions", "consolidation", "partnerships", "foreign currency transaction", "translation", "segment reporting"],
    "ACCT 5410": ["EDP Auditing and Control", "Introductory Auditing", "professional standards", "internal", "external audit", "advanced topics", "auditing judgments", "Materials fee required"],
    "ACCT 5440": ["Accounting Law, Ethics and Institutions", "advanced accounting law topics", "ethical standards", "political", "regulatory institutions", "public accounting profession"],
    "ACCT 5470": ["Advanced Cost Accounting", "Product costing", "service costing", "overhead analysis", "multiple allocation techniques", "joint costs", "byproducts", "spoilage", "rework", "scrap", "Alternative costing systems", "operations costing", "process costing", "Valuation of inventory", "just-in-time inventory management"],
    "ACCT 5560": ["Estates and Gifts, Ethics and other Specialized Taxation Topics", "Professional ethics", "tax practices", "gift", "estate tax", "income taxation of trusts and estates", "tax administration", "working with tax law", "advanced individual income tax topics"],
    "ACCT 5680": ["Accounting for Government and Not-for-Profit Organizations", "GASB accounting principles", "FASB financial reporting standards", "fair value accounting", "government financial statements"],
    "ACCT 5753": ["Accounting Internship", "supervised work", "study", "private", "public organizations", "may be repeated once for credit", "total of six units", "Graded credit/no credit"],
    "ACCT 5915": ["Seminar in Accounting", "intensive study", "topics change"],
    "ACCT 5930": ["Seminar in Accounting", "intensive study", "topics change"],
    "ACCT 5951": ["Independent Study", "library", "field research", "Consent of instructor", "approval by department", "total of 8 units", "cross-listed across different departments"],
    "ACCT 5952": ["Independent Study", "library", "field research", "Consent of instructor", "approval by department", "total of 8 units", "cross-listed across different departments"],
    "ACCT 5953": ["Independent Study", "library", "field research", "Consent of instructor", "approval by department", "total of 8 units", "cross-listed across different departments"],
    "ACCT 5955": ["Independent Study", "library", "field research", "Consent of instructor", "approval by department", "total of 8 units", "cross-listed across different departments"],
    "ACCT 6060": ["Accounting for Managerial Decision-Making", "financial information", "financial statements", "business decisions", "firm valuations", "investment decisions", "managerial decisions", "contracting", "Relevant practical cases"],
    "ACCT 6100": ["Financial Accounting from the User Perspective with Data Analytics in Accounting", "financial accounting", "user perspective", "reporting", "disclosing financial information", "accounting information manipulations", "data analytics"],
    "ACCT 6150": ["Controllership and Professional Ethics", "control systems", "Ethics", "Cost Behavior Analysis", "Balanced Scorecard", "Activity Based Management", "Target Costing", "Transfer Pricing", "Quality Cost", "Environmental Cost", "Performance Evaluation"],
    "ACCT 6200": ["Seminar in Advanced Auditing, Accounting Information Systems and Accounting Data Analytics", "CPA exam", "Principles of Auditing", "Becker CPA review", "Auditing & Fraud Case Studies"],
    "ACCT 6250": ["Advanced Internal Auditing", "evaluation", "organization's internal controls", "accounting processes", "corporate governance", "Internal Auditors", "timely and accurate financial reporting", "collection", "processing of data", "operational efficiency", "data integrity", "Certification available: CIA"],
    "ACCT 6300": ["Advanced Tax Topics: Corporate Taxation", "federal tax consequences", "formation", "operation", "reorganization", "liquidation of corporations", "taxation of S corporations"],
    "ACCT 6420": ["International Accounting", "developments", "international accounting", "similarities", "differences", "US GAAP", "international accounting standards", "social", "economic", "political influences"],
    "ACCT 6500": ["Advanced Financial Reporting Seminar", "accounting", "auditing standards", "regulations", "complex financial transactions", "case studies", "professional research"],
    "ACCT 6755": ["Internship", "supervised work", "study", "private", "public organizations", "may be repeated for credit", "total of six units", "Graded credit/no credit"],
    "ACCT 6960": ["MSA Project", "series of projects", "application of knowledge", "skills learned", "MSA program", "Graded credit/no credit"],
    "ACCT 6970": ["MSA Comprehensive Examination", "comprehensive exam", "Master of Science in Accountancy (Online)", "Weekly study guidelines", "assessment", "student's ability", "critical", "independent thinking", "demonstrate mastery", "final semester of coursework", "May be taken two times for six units"],
    "ACCT 6990": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "completion of requirements", "master's degree", "Consent of program coordinator", "Dean of Graduate Studies", "variable unit course", "Earned units are not degree-applicable"],
    "ACCT 6991": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "completion of requirements", "master's degree", "Consent of program coordinator", "Dean of Graduate Studies", "variable unit course", "Earned units are not degree-applicable"],
    "ACCT 6992": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "completion of requirements", "master's degree", "Consent of program coordinator", "Dean of Graduate Studies", "variable unit course", "Earned units are not degree-applicable"],
    "ACCT 6993": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "completion of requirements", "master's degree", "Consent of program coordinator", "Dean of Graduate Studies", "variable unit course", "Earned units are not degree-applicable"],
},

"FIN": {
    "FIN 5230": ["Security Trading and Analysis. An applied investment analysis course, emphasizing the application of modern portfolio theory and asset allocation models in selecting and evaluating stocks and bonds."],
    "FIN 5270": ["Financial Derivatives. Managing individual stock and stock portfolio price risks, interest rate risk, currency exchange-rate risk, and other financial risks using options, futures, forwards, and swaps. Emphasis on hedging risk than on speculative uses of financial derivatives."],
    "FIN 5460": ["Student Managed Investment Fund. Gain hands-on investment experience in managing real money. Learn to be an equity analyst and junior portfolio manager. Build an investment portfolio by selecting securities from the equity and bond markets."],
    "FIN 5555": ["Trade and Business in Asia. Introduction to religions, philosophies, cultures, characteristics, histories, and etiquettes of Asian countries from a business perspective. Topics also include the historical experiences and cultural contributions of Asian Americans to American society. As a practical approach to doing business with Asian countries and Asian communities, the course introduces international business practices including documentation, customs clearance procedures, shipping, the methods and instruments of payment, and international commercial terms."],
    "FIN 5600": ["Code of Ethics and Standards of Conduct in Financial Plan Development. CFP Board's code of Ethics and Standard of Conduct. This course covers the CFP Board's code of ethics and standard conduct, procedural rules, the structure of financial institutions, financial service regulations and requirements, consumer protection laws and fiduciary standards and applications, etc. This course also covers the creation and presentation of a financial plan."],
    "FIN 5753": ["Finance Internship. Supervised work and study in Financial function of private or public organizations. May be repeated once for credit. A total of six units of FIN 5753 (Finance Internship) course may be applied toward graduation. Graded credit/no credit. May be taken two times for six units."],
    "FIN 5755": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit."],
    "FIN 5850": ["Real Estate Finance. Financial aspects of real estate investment, including analysis of investment characteristics, lending environment, financial instruments, and effective loan proposals. Satisfies one of the state requirements toward the real estate broker license. Materials fee required."],
    "FIN 5860": ["Computer Applications in Real Estate. Introduction to computer skills for real estate. Topics covered include use of social media, professional networking, MS Office and Publisher, real estate presentation, contact management software, Multiple Listing Service, and real estate data analysis. Satisfies one of the state requirements toward the real estate broker license."],
    "FIN 5880": ["Real Estate Office Administration. Introduction to real estate office administration. Topics covered include recruiting salespeople for retention, selecting office personnel, written instruments between broker and salespeople, continual training, compensation and benefits, financial systems and records, market analysis, growth of a firm, etc. Satisfies one of the state requirements toward the real estate broker license."],
    "FIN 5915": ["Seminar in Finance. An intensive study of some phase of finance to be developed by the instructor. May be repeated for credit as topics change."],
    "FIN 5930": ["Seminar in Finance. An intensive study of some phase of finance to be developed by the instructor. May be repeated for credit as topics change."],
    "FIN 5951": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "FIN 5952": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken."],
    "FIN 5953": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken."],
    "FIN 5955": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "FIN 6020": ["Financial Theory and Corporate Finance. Modern finance theory and analysis of financial decision making. Topics include agency theory, time value of the money, risk and return, capital asset pricing model, capital market efficiency, bond and stock valuation, financial planning, cost of capital, capital budgeting, short-term financial management, capital structure, hybrid securities. Case studies are introduced."],
    "FIN 6220": ["Entrepreneurial and Venture Finance. An overview of the financial and investment of entrepreneurial firms. Focus is on financial and investment strategies available to entrepreneurial firms and the criteria for selecting the appropriate strategy."],
    "FIN 6510": ["Financial Institutions and Markets. Analysis of financial institutions and markets. Term structure of interest rates, portfolio theory and flow-fund analysis, deposit-type intermediaries, insurance, pension funds and investment companies, Federal Reserves System, and market regulation and policies."],
    "FIN 6530": ["Investment Analysis and Portfolio Management. Comprehensive introduction to the descriptive and formalized quantitative areas of security analysis, valuation, hedging, and portfolio management. This course includes activity in laboratory and a project analysis. Materials fee required."],
    "FIN 6540": ["International Finance. Study of international financial environment and problems in operation of multinational enterprises with major focus on theory and practice of foreign exchange transactions, money and capital markets, investment decisions, currency risk management, current asset management and comparative financial"],},

"ADMN": {
    "ADMN 5753": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit. "],
    "ADMN 5755": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit."],
    "ADMN 5910": ["Seminar in Administration. Intensive study of some phase of administration to be developed by instructor. May be repeated for credit as topics change. "],
    "ADMN 5915": ["Seminar in Administration. Intensive study of some phase of administration to be developed by instructor. May be repeated for credit as topics change."],
    "ADMN 5920": ["Seminar in Administration. Intensive study of some phase of administration to be developed by instructor. May be repeated for credit as topics change. "],
    "ADMN 5930": ["Seminar in Administration. Intensive study of some phase of administration to be developed by instructor. May be repeated for credit as topics change. "],
    "ADMN 5951": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "ADMN 5952": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. "],
    "ADMN 5953": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. "],
    "ADMN 5955": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "ADMN 6010": ["Data-Driven Decision Making. Advanced problem-solving qualitative and quantitative techniques to find, frame and solve difficult issues. "],
    "ADMN 6020": ["Advanced Managerial Communications. Introduces students to the principles of communication strategy and persuasion, with a focus on written and oral presentation assignments to increase student proficiency in managerial communication. Satisfies the graduate writing requirement. "],
    "ADMN 6753": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 6753 or 6755 courses may be applied toward graduation. Graded credit/no credit. "],
    "ADMN 6755": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit."],
    "ADMN 6901": ["Policy Management in Seoul: Seoul Case Study Program. This course provides students with the analysis of major issues in management of global cities, specifically Seoul Metropolitan Government, the Republic of Korea (South Korea). Topics include demographics, culture, social values, business practices, and urban development and civil service system of the Republic of Korea (South Korea). The course consists of (a) pre-visit in-class lectures and (b) visit Seoul Metropolitan Government, the Republic of Korea (lectures and field trips)."],
    "ADMN 6910": ["Advanced Topics in Administration. Intensive study of some advanced phase of administration to be developed by instructor. May be repeated for credit as topics change."],
    "ADMN 6915": ["Advanced Topics in Administration. Intensive study of some advanced phase of administration to be developed by instructor. May be repeated for credit as topics change."],
    "ADMN 6920": ["Advanced Topics in Administration. Intensive study of some advanced phase of administration to be developed by instructor. May be repeated for credit as topics change. "],
    "ADMN 6930": ["Advanced Topics in Administration. Intensive study of some advanced phase of administration to be developed by instructor. May be repeated for credit as topics change. "],
    "ADMN 6951": ["Directed Graduate Studies. Graduate-level independent study for students in Interdisciplinary Master of Arts programs; to be conducted under direct supervision of a faculty member from the students committee and, if an interdisciplinary studies major, with approval of the committee on graduate education and consent of the Dean of Graduate Studies. "],
    "ADMN 6952": ["Directed Graduate Studies. Graduate-level independent study for students in Interdisciplinary Master of Arts programs; to be conducted under direct supervision of a faculty member from the students committee and, if an interdisciplinary studies major, with approval of the committee on graduate education and consent of the Dean of Graduate Studies. "],},


"MGMT": {
    "MGMT 5755": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit."],
    "MGMT 5915": ["Contemporary Topics in Management. Analysis and discussion of selected topics relevant to managing effectively in the contemporary and dynamic business world. May be repeated for credit as topics change."],
    "MGMT 5930": ["Contemporary Topics in Management. Analysis and discussion of selected topics relevant to managing effectively in the contemporary and dynamic business world. "],
    "MGMT 5951": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "MGMT 5952": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. "],
    "MGMT 5953": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. "],
    "MGMT 5955": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "MGMT 6010": ["Organization Theory and Behavior. A critical analysis of theories for viewing organizations and an examination of the common models for understanding human behavior, including executive behavior, within the constraints of a complex social system. "],
    "MGMT 6500": ["International Management. Investigating factors important to the success of an organization planning or managing in an international setting, with emphasis on cultural, administrative, geographical, and economic differences and how to govern them. "],
    "MGMT 6550": ["Leadership as Art and Science. An overview of leadership emphasizing an understanding of the empirical research on classical and contemporary theories in the fields of leadership and followership and an application of theories designed to enhance employee well-being and organizational effectiveness. "],
    "MGMT 6755": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit."],
    "MGMT 6850": ["Strategic Management. Using fundamental concepts of strategy, this course examines an organization in the globalization context from the perspective of different stakeholders who together share the overall responsibility for the performance of the firm. Within the lens of PRME (Principles of Responsible Management Education) from the United Nations, the course is an innovative educational survey of selected topics from the field of strategy based on scholarly research and global practices that exemplify or deviate from the principles of responsible management. "],
    "MGMT 6990": ["Continuous Enrollment for Graduate Candidacy Standing. Independent study leading to completion of requirements (other than course work) for the master's degree. To retain classified standing in the master's program, a student must enroll in a Continuous Enrollment for Graduate Candidacy Standing course each quarter until the project or thesis is accepted or the comprehensive examination passed. Students who enroll through the university have full use of all university facilities. See Culminating Experience: Exam, Thesis, or Project in Graduate Degree and Program Requirements section of the Bulletin of Courses. Continuous Enrollment for Graduate Candidacy Standing is a variable unit course, see fee schedule in the Financial Information section of the Bulletin of Courses. Earned units are not degree-applicable nor will they qualify for financial aid."],
    "MGMT 6991": ["Continuous Enrollment for Graduate Candidacy Standing. Independent study leading to completion of requirements (other than course work) for the master's degree. To retain classified standing in the master's program, a student must enroll in a Continuous Enrollment for Graduate Candidacy Standing course each quarter until the project or thesis is accepted or the comprehensive examination passed. Students who enroll through the university have full use of all university facilities. See Culminating Experience: Exam, Thesis, or Project in Graduate Degree and Program Requirements section of the Bulletin of Courses. Continuous Enrollment for Graduate Candidacy Standing is a variable unit course, see fee schedule in the Financial Information section of the Bulletin of Courses. Earned units are not degree-applicable nor will they qualify for financial aid."],
},



"ENTR": {
    "ENTR 5155": ["Business Consulting. Supervised consulting assignments designed to provide meaningful business assistance to businesses. formerly offered as MGMT 515."],
    "ENTR 5260": ["Global Entrepreneurship. Entrepreneurial process in a global context as it relates to recognizing ideas, marshaling resources, developing networks and creating the strategy for a new cross-border venture. Formerly offered as MGMT 526."],
    "ENTR 5410": ["Commercializing Entrepreneurial Innovation. Examines the process of commercializing innovations and emerging technologies in entrepreneurial-driven companies. Focus on understanding the innovation process and the strategy, tactics and behaviors necessary to manage the transition from basic development stages to commercial venture; intellectual property law and protection, technology transfer and licensing. Formerly offered as ENTR 541."],
    "ENTR 5430": ["Ideation and Creative Problem Solving. Examination of the process of generating, developing and evaluating ideas to launch innovative and viable new ventures. Focus on identifying the difference between ideas and opportunities and the role of ideation, observation and creative problem solving. Formerly offered as ENTR 543."],
    "ENTR 5440": ["Developing the New Venture. Introduction to the process of developing a new venture concept. Focus on transitioning ideas into a viable business venture with special emphasis on developing a sustainable business model and a hands-on business planning experience. Formerly offered as ENTR 544."],
    "ENTR 5450": ["Resources for the Entrepreneur. Strategies and techniques employed by entrepreneurs to identify and access critical resources. Special emphasis on developing resource projections, negotiation, marshaling internal and external resources and team formation. Formerly offered as ENTR 545."],
    "ENTR 5470": ["Managing a Growing Business. Study of the basic strategy and tactics to manage growing enterprises while still maintaining an entrepreneurial spirit. Examines the role of management decision making, management control systems, short- and long-term planning, and entrepreneurship in managing growing companies. Formerly offered as ENTR 547."],
    "ENTR 5490": ["Launching the Entrepreneurial Venture. An exploration of the key processes and methods involved in positioning and establishing new enterprises. Formerly offered as ENTR 549."],
    "ENTR 5550": ["Entrepreneurship in Action: Corporate, Social and Family Business Approaches. An exploration of how entrepreneurial approaches are effectively applied in differing contexts, including large corporations, nonprofit organizations and closely-held family business firms. Focus on understanding the barriers and opportunities to entrepreneurship that are unique to each context through applied case analysis."],
    "ENTR 5755": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit."],
    "ENTR 5915": ["Contemporary Topics in Entrepreneurship. Analysis and discussion of selected topics relevant to entrepreneurship."],
    "ENTR 5930": ["Contemporary Topics in Entrepreneurship. Analysis and discussion of selected topics relevant to entrepreneurship. Formerly offered as MGMT 590C."],
    "ENTR 5951": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "ENTR 5952": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Formerly offered as 595B. Course is cross-listed across different departments within the college."],
    "ENTR 5953": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Formerly offered as 595D. Course is cross-listed across different departments within the college."],
    "ENTR 5955": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "ENTR 5980": ["Reflective Essay. Submission of a reflective essay based on specified program guidelines. Consent required. Graded credit/no credit. Formerly offered as ENTR 598."],
    "ENTR 6200": ["Pitching the New Venture. Introduction and exploration of the key concepts and techniques used to effectively position and deliver a concise summary of the opportunity, value proposition, business model, and investment potential of the new venture. Students will develop and pitch a multitude of entrepreneurial narratives for internal (business partners, leadership, management, employees) and external stakeholders (customers, public, investors, lenders)."],
    "ENTR 6210": ["Entrepreneurship and New Ventures. Study of the entrepreneurial process. Focus on the characteristics and mindset of entrepreneurs, ideation and innovation, startup models, risk mitigation, analyzing emerging opportunities, resource creativity, ethics and guerrilla tactics. Formerly offered as ENTR 621."],
    "ENTR 6230": ["Exploring Entrepreneurial Opportunities. Study of the exploration process for new venture concepts. Focus on examining the tools and processes involved in developing a new venture, including formulation of a sustainable business model, performing a comprehensive feasibility analysis, concept testing and business planning. Formerly offered as ENTR 623."],
    "ENTR 6240": ["Law and Negotiations for the New Venture. Introduction, exploration and analysis of the key legal, regulatory and policy issues that affect new venture decision-making, negotiations and strategy."],
},


"HRM": {
    "HRM 5570": ["Strategic Human Resource Management. Capstone course integrating human resource management materials acquired through the required concentration courses and addressing the strategic role of HR professionals in organizations. Formerly offered as HRM 470, HRM 4700."],
    "HRM 5580": ["California Human Resources. Current laws, legal rulings, and regulations with a California specific emphasis."],
    "HRM 5590": ["International Human Resources. Discuss global business, international staffing assignments, and leaders for global organizations."],
    "HRM 5755": ["Internship. Supervised work and study in private or public organizations. May be repeated for credit. A total of six units of Jack H. Brown College of Business and Public Administration 5753 or 5755 courses may be applied toward graduation. Graded credit/no credit."],
    "HRM 5915": ["Contemporary Topics in Human Resources Management. Analysis and discussion of selected topics relevant to managing human resources effectively in the contemporary and dynamic business world. May be repeated for credit as topics change."],
    "HRM 5930": ["Contemporary Topics in Human Resources Management. Analysis and discussion of selected topics relevant to managing human resources effectively in the contemporary and dynamic business world. May be repeated for credit as topics change."],
    "HRM 5951": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "HRM 5952": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Formerly offered as 595B. Course is cross-listed across different departments within the college."],
    "HRM 5953": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Formerly offered as 595D. Course is cross-listed across different departments within the college."],
    "HRM 5955": ["Independent Study. Special topics involving library and/or field research. A total of 8 units in any Jack H. Brown College of Business and Public Administration 5951, 5952, 5953, 5955 may be applied toward graduation. Consent of instructor and approval by the department of a written project/proposal submitted to the appropriate department in the Jack H. Brown College of Business and Public Administration on a standard application filed in advance of the semester in which the course is to be taken. Course is cross-listed across different departments within the college."],
    "HRM 6410": ["Human Resource Management. Analysis of specific areas of human resource management. Topics include strategic human resource management, staffing, performance management, compensation, labor relations and human resource development. Formerly offered as MGMT 641, MGMT 6410."]   
},


"MKTG": {
    "MKTG 5160": ["Marketing Data Analytics", "business analytic opportunities", "big data", "new insights", "statistical methods", "data analysts", "business decisions", "data literacy", "strategic decisions", "data"],
    "MKTG 5200": ["Advanced Marketing Communication", "marketing communication", "advertising", "direct marketing", "personal selling", "public relations", "sales promotion", "digital strategies", "global", "ethical", "integration", "coordination"],
    "MKTG 5250": ["Sports and Entertainment Marketing", "marketing", "sports", "entertainment", "sponsorship", "endorsement", "licensing", "strategic marketing plans", "situational analysis", "SWOT analysis", "mission statement", "positioning statement"],
    "MKTG 5500": ["Advanced Sports Marketing Planning and Strategy", "strategic sports marketing management", "situation analysis", "strategic marketing alternatives", "marketing plans", "implementation", "sports industry"],
    "MKTG 5550": ["Advanced Entertainment Marketing Planning and Strategy", "strategic entertainment marketing management", "situation analysis", "strategic marketing alternatives", "marketing plans", "implementation", "entertainment industry"],
    "MKTG 5600": ["Experiential Marketing", "service marketing", "service quality", "customer satisfaction", "marketing of services", "service excellence", "goods and services"],
    "MKTG 5700": ["Hospitality Operations Management", "hospitality industry", "management functions", "quality assurance", "guest satisfaction", "process improvement", "managers", "operational assessment", "trends"],
    "MKTG 5720": ["Hotel Operations and Service Management", "hotel management", "room reservations", "housekeeping", "front desk management", "service quality", "pricing", "inventory management"],
    "MKTG 5730": ["Festival and Entertainment Management", "attraction-based events", "scheduling", "financing", "budgeting", "revenue distribution", "logistics", "marketing", "contracts", "staging"],
    "MKTG 5740": ["Tribal Gaming: Cultural and Political Context", "tribal gaming", "American Indian", "economic development", "sociocultural", "political relationships", "federal government", "tribal governments", "societal responses"],
    "MKTG 5750": ["Hospitality Internship I", "internship", "hotel", "restaurant", "experience", "rotation", "departments"],
    "MKTG 5752": ["Hospitality Internship II", "internship", "food handler certification", "restaurant experience", "hotel", "tribal casino", "tourism site", "work", "project"],
    "MKTG 5755": ["Internship", "supervised work", "study", "organizations", "repeated for credit"],
    "MKTG 5915": ["Seminar in Marketing", "intensive study", "marketing phase", "instructor", "repeated for credit"],
    "MKTG 5930": ["Seminar in Marketing", "intensive study", "marketing phase", "instructor", "repeated for credit"],
    "MKTG 5951": ["Independent Study", "special topics", "library research", "field research", "project/proposal", "cross-listed departments"],
    "MKTG 5952": ["Independent Study", "special topics", "library research", "field research", "project/proposal", "cross-listed departments"],
    "MKTG 5953": ["Independent Study", "special topics", "library research", "field research", "project/proposal", "cross-listed departments"],
    "MKTG 5955": ["Independent Study", "special topics", "library research", "field research", "project/proposal", "cross-listed departments"],
    "MKTG 6050": ["Marketing Management", "managerial decision-making", "problem-solving", "marketing mix", "selling", "advertising", "pricing", "consumer behavior", "channels of distribution"],
    "MKTG 6100": ["Consumer and Organizational Buying Behavior", "purchasing behavior", "consumers", "organizational buyers", "theories", "public policy decisions"],
    "MKTG 6400": ["Advanced Marketing Research", "marketing research methods", "data analysis", "problem definition", "research design", "statistical software packages"],
    "MKTG 6500": ["E-Commerce", "e-commerce", "business models", "digital marketing", "online payment systems", "privacy issues"],
    "MKTG 6700": ["Global Marketing Strategies", "global markets", "international markets", "marketing strategies", "international changes"],
    "MKTG 6755": ["Internship", "supervised work", "study", "organizations", "repeated for credit"],
    "MKTG 6900": ["Marketing Strategy", "strategy planning", "marketing management", "decision-making process", "self-analysis", "external analysis", "legal", "ethical", "international aspects"],
    "MKTG 6990": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree", "classified standing", "comprehensive examination"],
    "MKTG 6991": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree", "classified standing", "comprehensive examination"],
    "MKTG 6992": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree", "classified standing", "comprehensive examination"],
    "MKTG 6993": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree", "classified standing", "comprehensive examination"],
    "MKTG 6994": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree", "classified standing", "comprehensive examination"],
    "MKTG 6995": ["Continuous Enrollment for Graduate Candidacy Standing", "independent study", "master's degree", "classified standing", "comprehensive examination"],
}


}

